<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

/**
 * The remaining maintained locales for the runtime-app tabs. English, Turkish,
 * Polish and Chinese shipped before this; here are the other twenty-six, so no
 * customer sees the Laravel/Node.js/Python tabs fall back to English. Product
 * names (Laravel, Node.js, Python) stay as they are everywhere.
 */
return new class extends Migration
{
    private function rows(): array
    {
        return [
            'ar' => ['hosting.laravel.title' => 'تطبيقات Laravel', 'hosting.laravel.subtitle' => 'تطبيقات Laravel الخاصة بك على هذه الاستضافة.', 'hosting.nodejs.title' => 'تطبيقات Node.js', 'hosting.nodejs.subtitle' => 'تطبيقات Node.js الخاصة بك على هذه الاستضافة.', 'hosting.python.title' => 'تطبيقات Python', 'hosting.python.subtitle' => 'تطبيقات Python الخاصة بك على هذه الاستضافة.', 'hosting.runtime.domain' => 'النطاق', 'hosting.runtime.version' => 'الإصدار', 'hosting.runtime.open' => 'فتح', 'hosting.runtime.empty_title' => 'لا توجد تطبيقات بعد', 'hosting.runtime.empty_hint' => 'أنشئ التطبيقات وانشرها من لوحة تحكم الاستضافة.'],
            'az' => ['hosting.laravel.title' => 'Laravel Tətbiqləri', 'hosting.laravel.subtitle' => 'Bu hostinqdəki Laravel tətbiqləriniz.', 'hosting.nodejs.title' => 'Node.js Tətbiqləri', 'hosting.nodejs.subtitle' => 'Bu hostinqdəki Node.js tətbiqləriniz.', 'hosting.python.title' => 'Python Tətbiqləri', 'hosting.python.subtitle' => 'Bu hostinqdəki Python tətbiqləriniz.', 'hosting.runtime.domain' => 'Domen', 'hosting.runtime.version' => 'Versiya', 'hosting.runtime.open' => 'Aç', 'hosting.runtime.empty_title' => 'Hələ tətbiq yoxdur', 'hosting.runtime.empty_hint' => 'Tətbiqləri hostinq idarə panelinizdən yaradın və yerləşdirin.'],
            'ca' => ['hosting.laravel.title' => 'Aplicacions Laravel', 'hosting.laravel.subtitle' => 'Les teves aplicacions Laravel en aquest allotjament.', 'hosting.nodejs.title' => 'Aplicacions Node.js', 'hosting.nodejs.subtitle' => 'Les teves aplicacions Node.js en aquest allotjament.', 'hosting.python.title' => 'Aplicacions Python', 'hosting.python.subtitle' => 'Les teves aplicacions Python en aquest allotjament.', 'hosting.runtime.domain' => 'Domini', 'hosting.runtime.version' => 'Versió', 'hosting.runtime.open' => 'Obre', 'hosting.runtime.empty_title' => 'Encara no hi ha aplicacions', 'hosting.runtime.empty_hint' => 'Crea i desplega aplicacions des del tauler de control del teu allotjament.'],
            'cs' => ['hosting.laravel.title' => 'Aplikace Laravel', 'hosting.laravel.subtitle' => 'Vaše aplikace Laravel na tomto hostingu.', 'hosting.nodejs.title' => 'Aplikace Node.js', 'hosting.nodejs.subtitle' => 'Vaše aplikace Node.js na tomto hostingu.', 'hosting.python.title' => 'Aplikace Python', 'hosting.python.subtitle' => 'Vaše aplikace Python na tomto hostingu.', 'hosting.runtime.domain' => 'Doména', 'hosting.runtime.version' => 'Verze', 'hosting.runtime.open' => 'Otevřít', 'hosting.runtime.empty_title' => 'Zatím žádné aplikace', 'hosting.runtime.empty_hint' => 'Vytvářejte a nasazujte aplikace z ovládacího panelu hostingu.'],
            'da' => ['hosting.laravel.title' => 'Laravel-apps', 'hosting.laravel.subtitle' => 'Dine Laravel-applikationer på dette webhotel.', 'hosting.nodejs.title' => 'Node.js-apps', 'hosting.nodejs.subtitle' => 'Dine Node.js-applikationer på dette webhotel.', 'hosting.python.title' => 'Python-apps', 'hosting.python.subtitle' => 'Dine Python-applikationer på dette webhotel.', 'hosting.runtime.domain' => 'Domæne', 'hosting.runtime.version' => 'Version', 'hosting.runtime.open' => 'Åbn', 'hosting.runtime.empty_title' => 'Ingen applikationer endnu', 'hosting.runtime.empty_hint' => 'Opret og udrul applikationer fra dit webhotels kontrolpanel.'],
            'de' => ['hosting.laravel.title' => 'Laravel-Apps', 'hosting.laravel.subtitle' => 'Ihre Laravel-Anwendungen auf diesem Hosting.', 'hosting.nodejs.title' => 'Node.js-Apps', 'hosting.nodejs.subtitle' => 'Ihre Node.js-Anwendungen auf diesem Hosting.', 'hosting.python.title' => 'Python-Apps', 'hosting.python.subtitle' => 'Ihre Python-Anwendungen auf diesem Hosting.', 'hosting.runtime.domain' => 'Domain', 'hosting.runtime.version' => 'Version', 'hosting.runtime.open' => 'Öffnen', 'hosting.runtime.empty_title' => 'Noch keine Anwendungen', 'hosting.runtime.empty_hint' => 'Erstellen und veröffentlichen Sie Anwendungen über Ihr Hosting-Control-Panel.'],
            'el' => ['hosting.laravel.title' => 'Εφαρμογές Laravel', 'hosting.laravel.subtitle' => 'Οι εφαρμογές σας Laravel σε αυτή τη φιλοξενία.', 'hosting.nodejs.title' => 'Εφαρμογές Node.js', 'hosting.nodejs.subtitle' => 'Οι εφαρμογές σας Node.js σε αυτή τη φιλοξενία.', 'hosting.python.title' => 'Εφαρμογές Python', 'hosting.python.subtitle' => 'Οι εφαρμογές σας Python σε αυτή τη φιλοξενία.', 'hosting.runtime.domain' => 'Τομέας', 'hosting.runtime.version' => 'Έκδοση', 'hosting.runtime.open' => 'Άνοιγμα', 'hosting.runtime.empty_title' => 'Δεν υπάρχουν ακόμη εφαρμογές', 'hosting.runtime.empty_hint' => 'Δημιουργήστε και αναπτύξτε εφαρμογές από τον πίνακα ελέγχου της φιλοξενίας σας.'],
            'es' => ['hosting.laravel.title' => 'Aplicaciones Laravel', 'hosting.laravel.subtitle' => 'Tus aplicaciones Laravel en este alojamiento.', 'hosting.nodejs.title' => 'Aplicaciones Node.js', 'hosting.nodejs.subtitle' => 'Tus aplicaciones Node.js en este alojamiento.', 'hosting.python.title' => 'Aplicaciones Python', 'hosting.python.subtitle' => 'Tus aplicaciones Python en este alojamiento.', 'hosting.runtime.domain' => 'Dominio', 'hosting.runtime.version' => 'Versión', 'hosting.runtime.open' => 'Abrir', 'hosting.runtime.empty_title' => 'Aún no hay aplicaciones', 'hosting.runtime.empty_hint' => 'Crea e implementa aplicaciones desde el panel de control de tu alojamiento.'],
            'et' => ['hosting.laravel.title' => 'Laraveli rakendused', 'hosting.laravel.subtitle' => 'Teie Laraveli rakendused sellel majutusel.', 'hosting.nodejs.title' => 'Node.js rakendused', 'hosting.nodejs.subtitle' => 'Teie Node.js rakendused sellel majutusel.', 'hosting.python.title' => 'Pythoni rakendused', 'hosting.python.subtitle' => 'Teie Pythoni rakendused sellel majutusel.', 'hosting.runtime.domain' => 'Domeen', 'hosting.runtime.version' => 'Versioon', 'hosting.runtime.open' => 'Ava', 'hosting.runtime.empty_title' => 'Rakendusi veel pole', 'hosting.runtime.empty_hint' => 'Looge ja juurutage rakendusi oma majutuse juhtpaneelist.'],
            'fa' => ['hosting.laravel.title' => 'برنامه‌های Laravel', 'hosting.laravel.subtitle' => 'برنامه‌های Laravel شما روی این هاست.', 'hosting.nodejs.title' => 'برنامه‌های Node.js', 'hosting.nodejs.subtitle' => 'برنامه‌های Node.js شما روی این هاست.', 'hosting.python.title' => 'برنامه‌های Python', 'hosting.python.subtitle' => 'برنامه‌های Python شما روی این هاست.', 'hosting.runtime.domain' => 'دامنه', 'hosting.runtime.version' => 'نسخه', 'hosting.runtime.open' => 'باز کردن', 'hosting.runtime.empty_title' => 'هنوز برنامه‌ای نیست', 'hosting.runtime.empty_hint' => 'برنامه‌ها را از کنترل‌پنل هاست خود ایجاد و مستقر کنید.'],
            'fi' => ['hosting.laravel.title' => 'Laravel-sovellukset', 'hosting.laravel.subtitle' => 'Laravel-sovelluksesi tällä hostingilla.', 'hosting.nodejs.title' => 'Node.js-sovellukset', 'hosting.nodejs.subtitle' => 'Node.js-sovelluksesi tällä hostingilla.', 'hosting.python.title' => 'Python-sovellukset', 'hosting.python.subtitle' => 'Python-sovelluksesi tällä hostingilla.', 'hosting.runtime.domain' => 'Verkkotunnus', 'hosting.runtime.version' => 'Versio', 'hosting.runtime.open' => 'Avaa', 'hosting.runtime.empty_title' => 'Ei vielä sovelluksia', 'hosting.runtime.empty_hint' => 'Luo ja julkaise sovelluksia hostingin hallintapaneelista.'],
            'fr' => ['hosting.laravel.title' => 'Applications Laravel', 'hosting.laravel.subtitle' => 'Vos applications Laravel sur cet hébergement.', 'hosting.nodejs.title' => 'Applications Node.js', 'hosting.nodejs.subtitle' => 'Vos applications Node.js sur cet hébergement.', 'hosting.python.title' => 'Applications Python', 'hosting.python.subtitle' => 'Vos applications Python sur cet hébergement.', 'hosting.runtime.domain' => 'Domaine', 'hosting.runtime.version' => 'Version', 'hosting.runtime.open' => 'Ouvrir', 'hosting.runtime.empty_title' => 'Aucune application pour le moment', 'hosting.runtime.empty_hint' => 'Créez et déployez des applications depuis le panneau de contrôle de votre hébergement.'],
            'he' => ['hosting.laravel.title' => 'אפליקציות Laravel', 'hosting.laravel.subtitle' => 'אפליקציות Laravel שלך באחסון זה.', 'hosting.nodejs.title' => 'אפליקציות Node.js', 'hosting.nodejs.subtitle' => 'אפליקציות Node.js שלך באחסון זה.', 'hosting.python.title' => 'אפליקציות Python', 'hosting.python.subtitle' => 'אפליקציות Python שלך באחסון זה.', 'hosting.runtime.domain' => 'דומיין', 'hosting.runtime.version' => 'גרסה', 'hosting.runtime.open' => 'פתח', 'hosting.runtime.empty_title' => 'אין עדיין אפליקציות', 'hosting.runtime.empty_hint' => 'צור ופרוס אפליקציות מלוח הבקרה של האחסון שלך.'],
            'hr' => ['hosting.laravel.title' => 'Laravel aplikacije', 'hosting.laravel.subtitle' => 'Vaše Laravel aplikacije na ovom hostingu.', 'hosting.nodejs.title' => 'Node.js aplikacije', 'hosting.nodejs.subtitle' => 'Vaše Node.js aplikacije na ovom hostingu.', 'hosting.python.title' => 'Python aplikacije', 'hosting.python.subtitle' => 'Vaše Python aplikacije na ovom hostingu.', 'hosting.runtime.domain' => 'Domena', 'hosting.runtime.version' => 'Verzija', 'hosting.runtime.open' => 'Otvori', 'hosting.runtime.empty_title' => 'Još nema aplikacija', 'hosting.runtime.empty_hint' => 'Izradite i implementirajte aplikacije iz upravljačke ploče hostinga.'],
            'hu' => ['hosting.laravel.title' => 'Laravel alkalmazások', 'hosting.laravel.subtitle' => 'A Laravel alkalmazásaid ezen a tárhelyen.', 'hosting.nodejs.title' => 'Node.js alkalmazások', 'hosting.nodejs.subtitle' => 'A Node.js alkalmazásaid ezen a tárhelyen.', 'hosting.python.title' => 'Python alkalmazások', 'hosting.python.subtitle' => 'A Python alkalmazásaid ezen a tárhelyen.', 'hosting.runtime.domain' => 'Domain', 'hosting.runtime.version' => 'Verzió', 'hosting.runtime.open' => 'Megnyitás', 'hosting.runtime.empty_title' => 'Még nincsenek alkalmazások', 'hosting.runtime.empty_hint' => 'Hozz létre és telepíts alkalmazásokat a tárhely vezérlőpultjából.'],
            'it' => ['hosting.laravel.title' => 'App Laravel', 'hosting.laravel.subtitle' => 'Le tue applicazioni Laravel su questo hosting.', 'hosting.nodejs.title' => 'App Node.js', 'hosting.nodejs.subtitle' => 'Le tue applicazioni Node.js su questo hosting.', 'hosting.python.title' => 'App Python', 'hosting.python.subtitle' => 'Le tue applicazioni Python su questo hosting.', 'hosting.runtime.domain' => 'Dominio', 'hosting.runtime.version' => 'Versione', 'hosting.runtime.open' => 'Apri', 'hosting.runtime.empty_title' => 'Nessuna applicazione ancora', 'hosting.runtime.empty_hint' => 'Crea e distribuisci applicazioni dal pannello di controllo del tuo hosting.'],
            'ja' => ['hosting.laravel.title' => 'Laravel アプリ', 'hosting.laravel.subtitle' => 'このホスティング上のあなたの Laravel アプリケーション。', 'hosting.nodejs.title' => 'Node.js アプリ', 'hosting.nodejs.subtitle' => 'このホスティング上のあなたの Node.js アプリケーション。', 'hosting.python.title' => 'Python アプリ', 'hosting.python.subtitle' => 'このホスティング上のあなたの Python アプリケーション。', 'hosting.runtime.domain' => 'ドメイン', 'hosting.runtime.version' => 'バージョン', 'hosting.runtime.open' => '開く', 'hosting.runtime.empty_title' => 'アプリケーションはまだありません', 'hosting.runtime.empty_hint' => 'ホスティングのコントロールパネルからアプリケーションを作成してデプロイします。'],
            'ko' => ['hosting.laravel.title' => 'Laravel 앱', 'hosting.laravel.subtitle' => '이 호스팅의 Laravel 애플리케이션입니다.', 'hosting.nodejs.title' => 'Node.js 앱', 'hosting.nodejs.subtitle' => '이 호스팅의 Node.js 애플리케이션입니다.', 'hosting.python.title' => 'Python 앱', 'hosting.python.subtitle' => '이 호스팅의 Python 애플리케이션입니다.', 'hosting.runtime.domain' => '도메인', 'hosting.runtime.version' => '버전', 'hosting.runtime.open' => '열기', 'hosting.runtime.empty_title' => '아직 애플리케이션이 없습니다', 'hosting.runtime.empty_hint' => '호스팅 제어판에서 애플리케이션을 만들고 배포하세요.'],
            'mk' => ['hosting.laravel.title' => 'Laravel апликации', 'hosting.laravel.subtitle' => 'Вашите Laravel апликации на овој хостинг.', 'hosting.nodejs.title' => 'Node.js апликации', 'hosting.nodejs.subtitle' => 'Вашите Node.js апликации на овој хостинг.', 'hosting.python.title' => 'Python апликации', 'hosting.python.subtitle' => 'Вашите Python апликации на овој хостинг.', 'hosting.runtime.domain' => 'Домен', 'hosting.runtime.version' => 'Верзија', 'hosting.runtime.open' => 'Отвори', 'hosting.runtime.empty_title' => 'Сè уште нема апликации', 'hosting.runtime.empty_hint' => 'Создавајте и распоредувајте апликации од контролниот панел на вашиот хостинг.'],
            'nl' => ['hosting.laravel.title' => 'Laravel-apps', 'hosting.laravel.subtitle' => 'Uw Laravel-applicaties op deze hosting.', 'hosting.nodejs.title' => 'Node.js-apps', 'hosting.nodejs.subtitle' => 'Uw Node.js-applicaties op deze hosting.', 'hosting.python.title' => 'Python-apps', 'hosting.python.subtitle' => 'Uw Python-applicaties op deze hosting.', 'hosting.runtime.domain' => 'Domein', 'hosting.runtime.version' => 'Versie', 'hosting.runtime.open' => 'Openen', 'hosting.runtime.empty_title' => 'Nog geen applicaties', 'hosting.runtime.empty_hint' => 'Maak en implementeer applicaties vanuit uw hostingconfiguratiescherm.'],
            'no' => ['hosting.laravel.title' => 'Laravel-apper', 'hosting.laravel.subtitle' => 'Dine Laravel-applikasjoner på denne hostingen.', 'hosting.nodejs.title' => 'Node.js-apper', 'hosting.nodejs.subtitle' => 'Dine Node.js-applikasjoner på denne hostingen.', 'hosting.python.title' => 'Python-apper', 'hosting.python.subtitle' => 'Dine Python-applikasjoner på denne hostingen.', 'hosting.runtime.domain' => 'Domene', 'hosting.runtime.version' => 'Versjon', 'hosting.runtime.open' => 'Åpne', 'hosting.runtime.empty_title' => 'Ingen applikasjoner ennå', 'hosting.runtime.empty_hint' => 'Opprett og distribuer applikasjoner fra hostingens kontrollpanel.'],
            'pt-br' => ['hosting.laravel.title' => 'Aplicativos Laravel', 'hosting.laravel.subtitle' => 'Seus aplicativos Laravel nesta hospedagem.', 'hosting.nodejs.title' => 'Aplicativos Node.js', 'hosting.nodejs.subtitle' => 'Seus aplicativos Node.js nesta hospedagem.', 'hosting.python.title' => 'Aplicativos Python', 'hosting.python.subtitle' => 'Seus aplicativos Python nesta hospedagem.', 'hosting.runtime.domain' => 'Domínio', 'hosting.runtime.version' => 'Versão', 'hosting.runtime.open' => 'Abrir', 'hosting.runtime.empty_title' => 'Ainda não há aplicativos', 'hosting.runtime.empty_hint' => 'Crie e implante aplicativos pelo painel de controle da sua hospedagem.'],
            'ro' => ['hosting.laravel.title' => 'Aplicații Laravel', 'hosting.laravel.subtitle' => 'Aplicațiile tale Laravel pe această găzduire.', 'hosting.nodejs.title' => 'Aplicații Node.js', 'hosting.nodejs.subtitle' => 'Aplicațiile tale Node.js pe această găzduire.', 'hosting.python.title' => 'Aplicații Python', 'hosting.python.subtitle' => 'Aplicațiile tale Python pe această găzduire.', 'hosting.runtime.domain' => 'Domeniu', 'hosting.runtime.version' => 'Versiune', 'hosting.runtime.open' => 'Deschide', 'hosting.runtime.empty_title' => 'Încă nu există aplicații', 'hosting.runtime.empty_hint' => 'Creează și implementează aplicații din panoul de control al găzduirii tale.'],
            'ru' => ['hosting.laravel.title' => 'Приложения Laravel', 'hosting.laravel.subtitle' => 'Ваши приложения Laravel на этом хостинге.', 'hosting.nodejs.title' => 'Приложения Node.js', 'hosting.nodejs.subtitle' => 'Ваши приложения Node.js на этом хостинге.', 'hosting.python.title' => 'Приложения Python', 'hosting.python.subtitle' => 'Ваши приложения Python на этом хостинге.', 'hosting.runtime.domain' => 'Домен', 'hosting.runtime.version' => 'Версия', 'hosting.runtime.open' => 'Открыть', 'hosting.runtime.empty_title' => 'Приложений пока нет', 'hosting.runtime.empty_hint' => 'Создавайте и развертывайте приложения из панели управления хостингом.'],
            'sv' => ['hosting.laravel.title' => 'Laravel-appar', 'hosting.laravel.subtitle' => 'Dina Laravel-applikationer på detta webbhotell.', 'hosting.nodejs.title' => 'Node.js-appar', 'hosting.nodejs.subtitle' => 'Dina Node.js-applikationer på detta webbhotell.', 'hosting.python.title' => 'Python-appar', 'hosting.python.subtitle' => 'Dina Python-applikationer på detta webbhotell.', 'hosting.runtime.domain' => 'Domän', 'hosting.runtime.version' => 'Version', 'hosting.runtime.open' => 'Öppna', 'hosting.runtime.empty_title' => 'Inga applikationer ännu', 'hosting.runtime.empty_hint' => 'Skapa och distribuera applikationer från ditt webbhotells kontrollpanel.'],
            'uk' => ['hosting.laravel.title' => 'Застосунки Laravel', 'hosting.laravel.subtitle' => 'Ваші застосунки Laravel на цьому хостингу.', 'hosting.nodejs.title' => 'Застосунки Node.js', 'hosting.nodejs.subtitle' => 'Ваші застосунки Node.js на цьому хостингу.', 'hosting.python.title' => 'Застосунки Python', 'hosting.python.subtitle' => 'Ваші застосунки Python на цьому хостингу.', 'hosting.runtime.domain' => 'Домен', 'hosting.runtime.version' => 'Версія', 'hosting.runtime.open' => 'Відкрити', 'hosting.runtime.empty_title' => 'Застосунків ще немає', 'hosting.runtime.empty_hint' => 'Створюйте та розгортайте застосунки з панелі керування хостингом.'],
        ];
    }

    public function up(): void
    {
        $now = now();
        foreach ($this->rows() as $lang => $pairs) {
            foreach ($pairs as $key => $value) {
                if (! DB::table('dynamic_translations')->where('language', $lang)->where('group', 'client')->where('key', $key)->exists()) {
                    DB::table('dynamic_translations')->insert(['language' => $lang, 'group' => 'client', 'key' => $key, 'value' => $value, 'is_auto_translated' => false, 'is_reviewed' => true, 'created_at' => $now, 'updated_at' => $now]);
                }
            }
            Cache::forget("translations:{$lang}:client");
        }
    }

    public function down(): void
    {
        foreach ($this->rows() as $lang => $pairs) {
            DB::table('dynamic_translations')->where('language', $lang)->where('group', 'client')->whereIn('key', array_keys($pairs))->delete();
        }
    }
};
