<?php

/*
 * Hand-written "key parameters" strings for the API reference screen.
 *
 * The endpoint LIST on that screen is not written here or anywhere else by
 * hand - it is read from the live route table, so it cannot drift from the
 * code again (it once documented 26 endpoints that did not exist and left 91
 * real ones out). Only these short parameter hints are curated; an endpoint
 * missing from this file still appears on the screen, just without a hint.
 */
return [
    'acceptorder' => 'orderid (required)',
    'acceptquote' => 'quoteid (required)',
    'addannouncement' => 'title, announcement, published',
    'addclient' => 'firstname, lastname, email, password2 (optional - opens a portal login), address1, city, country, phonenumber',
    'addclientnote' => 'userid, note (required)',
    'addcontact' => 'clientid, email, firstname, lastname (required)',
    'addcredit' => 'clientid, description, amount (required)',
    'addinvoicepayment' => 'invoiceid, transid, gateway, date, amount (required)',
    'addorder' => 'clientid, pid[], billingcycle[], paymentmethod (required)',
    'addproduct' => 'name, gid, type, paytype (required)',
    'addprojectmessage' => 'projectid, message, adminid (required)',
    'addprojecttask' => 'projectid, title (required)',
    'addticketreply' => 'ticketid, message (required), adminid or clientid',
    'addtransaction' => 'clientid, invoiceid, description, amountin, amountout, gateway, date (required)',
    'applycredit' => 'invoiceid, amount (required), clientid (optional, must own the invoice)',
    'cancelorder' => 'orderid (required)',
    'createinvoice' => 'userid, date, duedate, itemdescription[], itemamount[], paymentmethod',
    'createproject' => 'title, adminid, clientid, status (required)',
    'createquote' => 'userid, subject, validuntil, lineitems (required)',
    'deleteclient' => 'clientid (required)',
    'deletecontact' => 'contactid (required)',
    'deleteorder' => 'orderid (required)',
    'deleteprojecttask' => 'projectid, taskid (required)',
    'deletequote' => 'quoteid (required)',
    'deleteticket' => 'ticketid (required)',
    'deleteticketreply' => 'ticketid, replyid (required)',
    'domainregister' => 'domainid (required)',
    'domainrelease' => 'domainid, newtag (required)',
    'domainrenew' => 'domainid (required)',
    'domaintransfer' => 'domainid (required)',
    'domainupdatelockingstatus' => 'domainid, lockstatus (required)',
    'domainwhois' => 'domain (required)',
    'fraudorder' => 'orderid (required)',
    'getannouncements' => 'limitnum, limitstart',
    'getclientpassword' => 'clientid (required)',
    'getclients' => 'search, limitnum, limitstart, sorting, orderby',
    'getclientsaddons' => 'clientid (required)',
    'getclientsdetails' => 'clientid or email (required)',
    'getclientsdomains' => 'clientid (required), limitnum, limitstart',
    'getclientsproducts' => 'clientid (required), limitnum, limitstart, pid, serviceid',
    'getcontacts' => 'userid (required)',
    'getinvoice' => 'invoiceid (required)',
    'getinvoices' => 'userid, status, limitnum, limitstart',
    'getorders' => 'userid, status, limitnum, limitstart',
    'getproducts' => 'pid, gid, module',
    'getproject' => 'projectid (required)',
    'getprojects' => 'limitnum, limitstart',
    'getquotes' => 'userid, status, limitnum, limitstart',
    'getsupportdepartments' => 'ignore_dept_assignments',
    'getsupportstatuses' => 'deptid',
    'getticket' => 'ticketid (required)',
    'gettickets' => 'clientid, deptid, status, limitnum, limitstart',
    'gettldpricing' => 'currencyid',
    'gettransactions' => 'clientid, invoiceid, limitnum, limitstart',
    'modulechangepackage' => 'serviceid (required)',
    'modulechangepw' => 'serviceid (required)',
    'modulecreate' => 'serviceid (required)',
    'modulesuspend' => 'serviceid (required)',
    'moduleterminate' => 'serviceid (required)',
    'moduleunsuspend' => 'serviceid (required)',
    'openticket' => 'deptid, clientid, subject, message (required)',
    'pendingorder' => 'orderid (required)',
    'sendadminemail' => 'subject, message',
    'sendemail' => 'messagename, id (clientid/serviceid/invoiceid depending on template)',
    'sendquote' => 'quoteid (required)',
    'updateclient' => 'clientid (required), any client field',
    'updateclientdomain' => 'domainid (required), expirydate, status, registrar, regdate',
    'updateclientproduct' => 'serviceid (required), any service field',
    'updatecontact' => 'contactid (required)',
    'updateinvoice' => 'invoiceid (required), status, date, duedate',
    'updateproject' => 'projectid (required)',
    'updateprojecttask' => 'projectid, taskid (required)',
    'updatequote' => 'quoteid (required)',
    'updateticket' => 'ticketid (required), status, subject, deptid',
    'validatelogin' => 'email, password (required)',
];
